version: "3.8" 
services:
  nginx-crm:
    build:
      context: .
      dockerfile: dockerfile-nginx
    image: nginx
    container_name: nginx-crmfin
    ports:
      - "8080:80"
    #  - "1080:1080"
    volumes:
      - ../docker_configs/nginx/nginx/:/etc/init.d/nginx
      - ../www/:/var/www/html/
      - ../docker_configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../logs/nginx/:/var/log/nginx/
    environment: 
      TZ: 'America/Sao_Paulo'
    links:
      - php
#      - mysql
#    command: sh -c "/etc/init.d/nginx start"
  php:
    build:
      context: .
      dockerfile: dockerfile-php
    image: php
    container_name: php-crmfin
    ports:
      - "9001:9000"
    volumes:
      - ../www/:/var/www/html/
      - ../docker_configs/php/:/usr/local/etc/php/
      - ../logs/php/:/php/
    environment: 
      TZ: 'America/Sao_Paulo'
    #command: sh -c "cron -f &"
    # links:
      # - mysql
  #mysql:
  #  image: percona
  #  container_name: mysql
  #  restart: always
  #  mem_limit: 2560m
  #  ports:
  #    - 3307:3306
  #  volumes:
  #    - ../../mysql_data/:/var/lib/mysql/
  #    - ../docker_configs/mysql/my.cnf:/etc/my.cnf.d/docker.cnf
  #    - ../../logs/mysql/log/:/var/log/mysql/
  #    
  #  environment:
  #    MYSQL_DATABASE: 'apicestat'
  #    MYSQL_USER: 'apice_stat'
  #    MYSQL_PASSWORD: 'Qvus995EAJ0INikKT4KH'
  #    MYSQL_ROOT_PASSWORD: 'Qvus995EAJ0INikKT4KH'
  #    TZ: 'America/Sao_Paulo'
#    image: mysql:8.0
#    container_name: mysql
#    ports:
#      - "3307:3306"
#    volumes:
#      - ../mysql_data/:/var/lib/mysql/
#    environment:
#      MYSQL_DATABASE: 'apicestat'
#      MYSQL_USER: 'root'
#      MYSQL_PASSWORD: 'root'
#     MYSQL_ROOT_PASSWORD: 'root'
#     TZ: 'America/Sao_Paulo'
#volumes:
#    mysql_data:  